import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Artigiano',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="bg-zinc-900">
      <body className={inter.className}>
        <div className="flex h-screen w-full">
          <Sidebar />
          <div className="ml-64 flex size-full flex-col">{children}</div>
        </div>
      </body>
    </html>
  )
}
